---
- hosts: "vms"
  become: true
  tasks:
    - name: ping_serv
      ping:

    - name: some_script
      ansible.builtin.shell: |
        echo 123
  roles:
  - soft
  - docker
  - create_sudo_user
  - delete_user
