Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"
  # config.vm.box_check_update = false

  config.vm.define "testvm" do |testvm|
    testvm.vm.network  "private_network", ip: "192.168.56.3", bridge: "enp44s0"
    testvm.vm.hostname = "testvm"
    testvm.vm.provider "virtualbox" do |vb|
       vb.memory = "6000"
       vb.cpus = 4  
       vb.gui = false
       vb.name = "testvm"
       end
  end

end
